Contoso.Apps.Movies.Web/Models/Cart/CartItemModel.cs
namespace Contoso.Apps.Movies.Web.Models
{
    public class CartItemModel
    {
        public int ItemId { get; set; }

        public string CartId { get; set; }

        public string CartItemId { get; set; }

        public int Quantity { get; set; }

        public System.DateTime DateCreated { get; set; }

        public string ProductProductName { get; set; }

        public string ProductImagePath { get; set; }

        public string ProductThumbnailPath { get; set; }

        public double? ProductUnitPrice { get; set; }
    }
}

Contoso.Apps.Movies.Web/Controllers/CheckoutController.cs
using AutoMapper;
using Contoso.Apps.Common;
using Contoso.Apps.Common.Controllers;
using Contoso.Apps.Movies.Data.Logic;
using Contoso.Apps.Movies.Data.Models;
using Contoso.Apps.Movies.Web.Helpers;
using Contoso.Apps.Movies.Web.Models;
using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Contoso.Apps.Movies.Web.Controllers
{
    [AllowAnonymous]
    public class CheckoutController : BaseController
    {
        public CheckoutController()
        {
            cartId = new Helpers.CartHelpers().GetCartId();
        }
        
        private readonly string cartId;

        // GET: Checkout
        public ActionResult Index()
        {
            var vm = new CheckoutModel();
            using (ShoppingCartActions usersShoppingCart = new ShoppingCartActions(cartId, items, categories))
            {
                var shoppingCartItems = usersShoppingCart.GetCartItems();
                var cartItemsVM = Mapper.Map<List<CartItemModel>>(shoppingCartItems);
                vm.CartItems = cartItemsVM;
                vm.OrderTotal = usersShoppingCart.GetTotal();
                vm.ItemsTotal = usersShoppingCart.GetCount();
            }

            // To make filling out the form faster for demo purposes, pre-fill the values:
            vm.Order = new OrderModel
            {
                // Important! Keep this property here!
                Total = vm.OrderTotal,
                // Prefill properties for convenience:
                FirstName = "Bob",
                LastName = "Loblaw",
                Address = "1313 Mockingbird Lane",
                City = "Virginia Beach",
                State = "VA",
                PostalCode = "23456",
                Country = "United States",
                Email = "bobloblaw@contosomovies.com",
                NameOnCard = "Bob Loblaw",
                CreditCardType = "Visa",
                CreditCardNumber = "4111111111111111",
                ExpirationDate = "12/20",
                CCV = "987",
                SMSOptIn = true
            };

            return View(vm);
        }

        // POST: Checkout/Start
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Review(CheckoutModel data)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    NVPAPICaller gatewayCaller = new NVPAPICaller();

                    string token = "";
                    NVPCodec decoder = new NVPCodec();

                    // Call the gateway payment authorization API:
                    bool ret = true;// gatewayCaller.DoCheckoutAuth(data.Order, ref token, ref decoder);

                    // If authorizaton is successful:
                    if (ret)
                    {
                        // Hydrate a new Order model from our OrderModel.
                        var myOrder = Mapper.Map<Data.Models.Order>(data.Order);
                        // Timestamp with a UTC date.
                        myOrder.OrderDate = DateTime.UtcNow;

                        // Add order to DB.
                        await SqlDbHelper.SaveOrder(myOrder);                        

                        // Get the shopping cart items and process them.
                        using (ShoppingCartActions usersShoppingCart = new ShoppingCartActions(cartId, items, categories))
                        {
                            List<CartItem> myOrderList = usersShoppingCart.GetCartItems();

                            // Add OrderDetail information to the DB for each product purchased.
                            for (int i = 0; i < myOrderList.Count; i++)
                            {
                                // Create a new OrderDetail object.
                                var myOrderDetail = new OrderDetail();
                                myOrderDetail.OrderDetailId = i;
                                myOrderDetail.OrderId = myOrder.OrderId;
                                myOrderDetail.ProductId = myOrderList[i].ItemId;
                                myOrderDetail.Quantity = myOrderList[i].Quantity;
                                myOrderDetail.UnitPrice = myOrderList[i].Product.UnitPrice;
                                myOrderDetail.Email = myOrder.Email;

                                // Add OrderDetail to DB.
                                await SqlDbHelper.SaveOrderDetails(myOrderDetail);
                            }

                            // Set OrderId.
                            Session["currentOrderId"] = myOrder.OrderId;
                            Session["Token"] = token;

                            // Report successful event to Application Insights.
                            var eventProperties = new Dictionary<string, string>();
                            eventProperties.Add("CustomerEmail", data.Order.Email);
                            eventProperties.Add("NumberOfItems", myOrderList.Count.ToString());
                            eventProperties.Add("OrderTotal", data.Order.Total.ToString("C2"));
                            eventProperties.Add("OrderId", myOrder.OrderId.ToString());
                            TelemetryHelper.TrackEvent("SuccessfulPaymentAuth", eventProperties);

                            data.Order.OrderId = myOrder.OrderId;

                            if (data.Order.CreditCardNumber.Length > 4)
                            {
                                // Only show the last 4 digits of the credit card number:
                                data.Order.CreditCardNumber = "xxxxxxxxxxx" + data.Order.CreditCardNumber.Substring(data.Order.CreditCardNumber.Length - 4);
                            }
                        }
                    }
                    else
                    {
                        var error = gatewayCaller.PopulateGatewayErrorModel(decoder);

                        // Report failed event to Application Insights.
                        Exception ex = new Exception(error.ToString());
                        ex.Source = "Contoso.Apps.Movies.Web.CheckoutController.cs";
                        TelemetryHelper.TrackException(ex);

                        // Redirect to the checkout error view:
                        return RedirectToAction("Error", error);
                    }
                }
                catch (WebException wex)
                {
                    ExceptionUtility.LogException(wex, "CheckoutController.cs Complete Action");

                    var error = new CheckoutErrorModel
                    {
                        ErrorCode = wex.Message
                    };

                    if (wex.Response != null && wex.Response.GetType() == typeof(HttpWebResponse))
                    {
                        // Extract the response body from the WebException's HttpWebResponse:
                        error.LongMessage = ((HttpWebResponse)wex.Response).StatusDescription;
                    }

                    // Redirect to the checkout error view:
                    return RedirectToAction("Error", error);
                }
                catch (Exception ex)
                {
                    ExceptionUtility.LogException(ex, "CheckoutController.cs Review Action");

                    var error = new CheckoutErrorModel
                    {
                        ErrorCode = ex.Message
                    };

                    // Redirect to the checkout error view:
                    return RedirectToAction("Error", error);
                }
            }

            return View(data);
        }

        // POST: Checkout/Complete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Complete(OrderModel order)
        {
            try
            {
                // TODO: Complete the payment processing via the gateway and update the order...
                NVPAPICaller gatewayCaller = new NVPAPICaller();

                string token = "";
                string finalPaymentAmount = "";
                NVPCodec decoder = new NVPCodec();

                token = Session["token"].ToString();
                //PayerID = Session["payerId"].ToString();
                //finalPaymentAmount = Session["payment_amt"].ToString();
                finalPaymentAmount = order.Total.ToString("C2");

                bool ret = true;// gatewayCaller.DoCheckoutPayment(finalPaymentAmount, token, ref decoder);
                if (ret)
                {
                    //// Retrieve PayPal confirmation value.
                    string PaymentConfirmation = Guid.NewGuid().ToString().Replace("-", "").Substring(0, 10);// decoder[NVPProperties.Properties.TRANSACTIONID].ToString();
                    order.PaymentTransactionId = PaymentConfirmation;

                    // Get the current order id.
                    int currentOrderId = -1;
                    if (Session["currentOrderId"] != null && Session["currentOrderId"].ToString() != string.Empty)
                    {
                        currentOrderId = Convert.ToInt32(Session["currentOrderID"]);
                    }

                    Order myCurrentOrder;

                    if (currentOrderId >= 0)
                    {
                        myCurrentOrder = await SqlDbHelper.GetOrder(currentOrderId);
                        
                        myCurrentOrder.PaymentTransactionId = PaymentConfirmation;

                        await SqlDbHelper.SaveOrder(myCurrentOrder);

                        // Queue up a receipt generation request, asynchronously.
                        await new AzureQueueHelper().QueueReceiptRequest(myCurrentOrder);

                        // Report successful event to Application Insights.
                        var eventProperties = new Dictionary<string, string>();

Contoso.Apps.Movies.Web/Controllers/StoreController.cs
using AutoMapper;
using Contoso.Apps.Common;
using Contoso.Apps.Common.Controllers;
using Contoso.Apps.Common.Extensions;
using Contoso.Apps.Movies.Data.Models;
using Contoso.Apps.Movies.Logic;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Contoso.Apps.Movies.Web.Controllers
{
    [AllowAnonymous]
    public class StoreController : BaseController
    {
        public StoreController()
        {
        }

        // GET: Store
        public ActionResult Index(string categoryId)
        {
            User user = (User)Session["User"];

            List<Item> products = new List<Item>();

            //only take 10 products...
            if (user != null)
            {
                string name = user.Email;
                int userId = user.UserId;
                products = RecommendationHelper.GetViaFunction("assoc", userId, 12);
            }
            else
            {
                products = RecommendationHelper.GetViaFunction("top", 0, 12);
            }

            var randomVm = Mapper.Map<List<Models.ProductListModel>>(RecommendationHelper.GetViaFunction("random", 0, 12));
            
            var productsVm = Mapper.Map<List<Models.ProductListModel>>(products);

            // Retrieve category listing:
            var categoriesVm = Mapper.Map<List<Models.CategoryModel>>(categories.ToList());

            var vm = new Models.StoreIndexModel
            {
                RandomProducts = randomVm,
                Products = productsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        public ActionResult Genre(int categoryId)
        {
            List<Item> products = SqlDbHelper.GetItemsByCategory(categoryId).ToList();

            var productsVm = Mapper.Map<List<Models.ProductListModel>>(products);

            // Retrieve category listing:
            var categoriesVm = Mapper.Map<List<Models.CategoryModel>>(categories.ToList());

            var vm = new Models.StoreIndexModel
            {
                Products = productsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        // GET: Store/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Item product = await SqlDbHelper.GetItem(id);

            if (product == null)
            {
                return HttpNotFound();
            }

            var productVm = Mapper.Map<Models.ProductModel>(product);

            //Get the simliar product to this item...
            var similarProducts = RecommendationHelper.GetViaFunction("content", 0, id.Value);
            var similarProductsVm = Mapper.Map<List<Models.ProductListModel>>(similarProducts);

            // Find related products, based on the category
            var relatedProducts = items.Where(p => p.CategoryId == product.CategoryId && p.ItemId != product.ItemId).Take(10).ToList();
            var relatedProductsVm = Mapper.Map<List<Models.ProductListModel>>(relatedProducts);

            // Retrieve category listing
            var categoriesVm = Mapper.Map<List<Models.CategoryModel>>(categories);

            // Retrieve "new products" as a list of three random products not equal to the displayed one
            var newProducts = items.Where(p => p.ItemId != product.ItemId).Take(50).ToList().Shuffle().Take(3);

            var newProductsVm = Mapper.Map<List<Models.ProductListModel>>(newProducts);

            var vm = new Models.StoreDetailsModel
            {
                Product = productVm,
                RelatedProducts = relatedProductsVm,
                SimilarProducts = similarProductsVm,
                NewProducts = newProductsVm,
                Categories = categoriesVm
            };

            return View(vm);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                
            }

            base.Dispose(disposing);
        }
    }
}

Contoso.Apps.Movies.Web/Views/Cart/Index.cshtml
@model Contoso.Apps.Movies.Web.Models.CartModel

@{
    ViewBag.Title = "Index";
}

@section HeaderOverlay {
    
}

<section class="store">
    <div class="container">
        <div class="row">
            <div class="wrapper clearfix">

                @if (Model.CartItems.Count > 0)
                {
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>
                                    Product Name
                                </th>
                                <th>
                                    Price
                                </th>
                                <th>
                                    Quantity
                                </th>
                                <th>
                                    Total
                                </th>
                                @*<th></th>*@
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.CartItems)
                            {
                                <tr>
                                    <td>
                                        <a href="@Url.Action("Details", "Store", new { id = item.ItemId })">
                                            <img src="@Url.Content("http://image.tmdb.org/t/p/w500/")@item.ProductImagePath" alt="@item.ProductProductName" class="center-block" style="width:100px">
                                        </a>
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Details", "Store", new { id = item.ItemId })">@Html.DisplayFor(modelItem => item.ProductProductName)</a>
                                    </td>
                                    <td>
                                        @String.Format("{0:c}", item.ProductUnitPrice)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td>
                                        @String.Format("{0:c}", (item.ProductUnitPrice.HasValue ? Math.Round(item.ProductUnitPrice.Value * item.Quantity, 2) : 0))
                                    </td>
                                    @*<td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.ItemId }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.ItemId }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.ItemId })
                                        </td>*@
                                </tr>
                            }
                        </tbody>
                    </table>

                    <hr />

                    <div class="row">
                        <div class="col-xs-6 col-sm-8 col-md-10 col-lg-11 text-right text-warning"><strong># of Items:</strong></div>
                        <div class="col-xs-6 col-sm-4 col-md-2 col-lg-1 text-warning">@Model.ItemsTotal</div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-8 col-md-10 col-lg-11 text-right text-warning"><strong>Total:</strong></div>
                        <div class="col-xs-6 col-sm-4 col-md-2 col-lg-1 text-warning">@String.Format("{0:c}", Model.OrderTotal)</div>
                    </div>
                    
                    <div class="row">
                        <div class="col-sm-12">
                            &nbsp;
                        </div>
                    </div>

                    <div class="pull-right">
                        <a href="@Url.Action("Index", "Checkout")" class="btn btn-primary">Checkout</a>
                    </div>

                    <div class="pull-left">
                        <a href="@Url.Action("Index", "Store")" class="btn trans-btn"><i class="fa fa-arrow-left"></i>&nbsp;&nbsp;Keep shopping</a>
                    </div>
                }
                else
                {
                    <div class="panel panel-warning">
                        <div class="panel-heading">
                            <h3 class="panel-title">Your shopping cart is empty</h3>
                        </div>
                        <div class="panel-body">
                            <p>Oops! You haven't added anything to your shopping cart yet!</p>
                            <p>You may have forgotten to add something to the cart. How about <a href="@Url.Action("Index", "Store")" style="color: blue">you take another look</a> at our selection of awesome products to try again?</p>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</section>